hmcts/div-case-maintenance-service

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
AwaitingLegalAdvisor state was missing from the Petitioner Retrieve State Map.
As such, retrieve-petition was returning 204 no case found for cases in AwaitingLegalAdvisor, the state after DN submission has occurred.
This is an issue since correct dynamic content on DN and redirection from D8 depends on the case being returned when its in the AwaitingLegalAdvisor state.
> Add AwaitingLegalAdvisor state to the Petitioner retrieve case list

- src/integrationTest/resources/ccd-submission-payload/addresses-no-hwf.json
- src/integrationTest/resources/ccd-submission-payload/addresses.json
- src/integrationTest/resources/ccd-submission-payload/d8-document.json
- src/integrationTest/resources/ccd-submission-payload/how-name-changed.json
- src/integrationTest/resources/ccd-submission-payload/jurisdiction-6-12.json
- src/integrationTest/resources/ccd-submission-payload/jurisdiction-all.json
- src/integrationTest/resources/ccd-submission-payload/linked-case.json
- src/integrationTest/resources/ccd-submission-payload/reason-adultery.json
- src/integrationTest/resources/ccd-submission-payload/reason-desertion.json
- src/integrationTest/resources/ccd-submission-payload/reason-separation.json
- src/integrationTest/resources/ccd-submission-payload/reason-unreasonable-behaviour.json
- src/integrationTest/resources/ccd-submission-payload/same-sex.json
- src/integrationTest/resources/ccd-update-payload/update-addresses.json
- src/test/resources/ccd-submission-payload/addresses-no-hwf.json
- src/test/resources/ccd-submission-payload/addresses.json
https://tools.hmcts.net/jira/browse/DIV-3830
Replaced instances of email@email.com with proper gov notify simulate-delivered email in integration tests
> DIV-3830: Replaced invalid emails with proper gov-notify one

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseByIdTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java
- src/integrationTest/resources/application.properties
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
Exposes another CCD citizen endpoint for use, to retrieve case details based on the case id passed in.
This is needed for the population of existing case data functionality needed for updates.
> Retrieve Petition by CaseId for Citizen

- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AuthIdamMockSupport.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdUpdateITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CreateDraftServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/DeleteDraftServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/GetCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/LinkRespondentITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAOSPostCompletedITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAllDraftsServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SaveDraftServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/UnlinkUserITest.java
Functional Unit Test keeps failing because Wiremock is unable to spin up local IDAM mock on localhost:4503 properly intermittently. This PR is to try and see if we can fix the issue consistently.
> Remove unused imports and fix Wiremock Content Cleanup on Functional Unit tests

- build.gradle
Bumped up jackson-databind version 2.9.8 to fix CVE-2018-14718 vulnerability
* Hardware:
* JDK:
> Force jackson-databind version 2.9.8

- Jenkinsfile_CNP
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdUpdateTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseByIdTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamTestSupport.java
- src/integrationTest/resources/application.properties
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/UserDetails.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdUpdateServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AuthIdamMockSupport.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdUpdateITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CreateDraftServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/DeleteDraftServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAllDraftsServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SaveDraftServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdUpdateServiceImplUTest.java
[DIV-3645](https://tools.hmcts.net/jira/browse/DIV-3645)
Strategic Payment is being implemented in div-case-orchestration service on PR https://github.com/hmcts/div-case-orchestration-service/pull/126.
However, we use an anonymous caseworker user in order to update the case passed to us by pay team.
The request by Pay team does not have an authorisation token, so we must use a user ourselves. When updating a case, either the citizen who created the case or a caseworker is required, so we use an anonymous caseworker user.
However, the update flow in COS is reused, but it only supports the citizen path. This PR changes the retrieve case by ID and update case code so it checks the current user (which will be the anonymous caseworker) has the caseworker role, and if they do, run the …
> Retrieve case by id regardless of role

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveAosCaseTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
For retrieving case for respondent, we shouldn't care whether that user has a saved draft
If a respondent already has a draft saved, CMS is retrieving that draft. However, as a respondent this feature should not be available.
Fixes # DIV-4252
Updated unit tests and integration tests
> DIV-4252: Fixing production error

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/LinkRespondentTest.java
- src/integrationTest/resources/ccd-submission-payload/linked-case.json
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/support/GlobalExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/exception/BaseException.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/exception/CaseNotFoundException.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/exception/DuplicateCaseException.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/exception/InvalidRequestException.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/exception/UnauthorizedException.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/support/GlobalExceptionHandlerUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/LinkRespondentITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/LinkRespondentServiceImplUTest.java
[Update linking process to only check respondent email field during linking](https://tools.hmcts.net/jira/browse/DIV-4494)
Parent ticket: [AOS / Co-Resp: use of 'received' and 'answer' fields is wrong.](https://tools.hmcts.net/jira/browse/DIV-4437)
No longer using the AoS Received fields to check if linking of case to respondent(s) is allowed. Now just use email field for respondent(s).
**Note: this also updates the errors being sent to make them more specific to root cause, helping with prod issues along the way.**
> DIV-4437 Linking respondents no longer check AoS Received

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CcdCaseProperties.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/DivorceSessionProperties.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
I was wrongly using the Divorce session attribute name, but actually I should be using the CCD attribute name since the field is inserted before the translation (by CFS).
Unit tests.
> DIV-4531: Fixing bug for amend petition previous date

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/config/HttpConnectionConfiguration.java
- src/test/resources/logback-test.xml
It's causing more than 1 million log messages in production
https://github.com/hmcts/java-logging/blob/master/java-logging-httpcomponents/src/main/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestLoggingInterceptor.java#L41
Also reduced test loggin to WARN
Before:
After:
Fixes #DIV-3956
> DIV-3956 - reduced logging noise

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/LinkRespondentTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CcdCaseProperties.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/LinkRespondentITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/LinkRespondentServiceImplUTest.java
[Prevent petitioner from linking as respondent](https://tools.hmcts.net/jira/browse/DIV-4871)
Bug-fix to prevent the petitioner linking as respondent, found in production issue.
> DIV-4871 Prevent petitioner linking to case as respondent

- charts/div-cms/values.aat.template.yaml
- charts/div-cms/values.preview.template.yaml
- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/variables.tf
To prevent hammering AAT, as every `/health` call checks _every_ dependent service, generating sometimes ~30 subsequent calls (e.g COS)
Tested locally via
`MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE=60000 ./gradlew clean bootrun`
> Override Spring's management endpoint cache to 30 seconds in AAT/Preview

- build.gradle
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
https://tools.hmcts.net/jira/browse/DIV-4920
Some case states are missing in state mapping, so the pfe is never redirected to dn
> Add missing complete states in petitioner mapping to fetch case state in pfe

- src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdBulkCaseUpdateTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java
There was a change to the scheduleForListing event used in the failing integration test that triggers a validation callback to check for future court hearing date. This fix adds that field into the test.
> Fix test bulk case hearing date

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseStateTest.java
Add DaRequested to prevent redirects to wrong FE when a respondent lands on the DA landing page with a state in DaRequested.
[DIV-5373](https://tools.hmcts.net/jira/browse/DIV-5373)
Ammend existing tests.
* Hardware:
* JDK:
> DIV-5373: Add state for DaRequested

- charts/div-cms/Chart.yaml
- charts/div-cms/requirements.yaml
- charts/div-cms/values.aat.template.yaml
- charts/div-cms/values.preview.template.yaml
- charts/div-cms/values.yaml
- src/main/resources/bootstrap.yaml
Reduced duplicated config values by moving them to values.yaml
And using {{ .Values.global.environment }} placeholder
Also removed unused env variables (if any)
See 
* https://github.com/hmcts/chart-java/pull/61 
* https://hmcts-reform.slack.com/archives/CLE7A3SKV/p1568286603003800
Fixes #DIV-5762
> DIV-5762 - use java chart v2.6.0 and reduced duplicated env references

- Jenkinsfile_CNP
- dependency-check-suppressions.xml
This will disable the legacy Azure deployment and switch over the DNS
To the new K8S prod cluster
Fixes #DIV-5762
> DIV-5762 - added disableLegacyDeployment() to switch deployment to AKS

- build.gradle
Updates Jackson Databind based on [this CVE issue](https://nvd.nist.gov/vuln/detail/CVE-2019-16942)
> Apply security fix Fix-CVE-2019-16942 Jackson

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CcdCaseProperties.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/DivorceSessionProperties.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionForRefusalDraftServiceITest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
https://tools.hmcts.net/jira/browse/DIV-5784
Adds previous reasons for divorce refusal field to draft (not using the existing field as that removes the option from being selectable from frontend)
> Add previous reasons for divorce mapping to refusal rejection

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImplUTest.java
Added and used a isEmpty() method to handle empty string values on solicitor details.
Fixes [RPET-11](https://tools.hmcts.net/jira/browse/RPET-11)
Unit tests added.
> isEmpty function added to handle empty string values on solicitor details

- build.gradle
Netty versions prior to 4.1.44 are vulnerable according to CVE-2019-20445 and others.
* Hardware:
* JDK:
> HOTFIX - Bump up Netty version to resolve CVE-2019-20445

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DraftStoreClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/FormatterServiceClient.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/DefaultHttpEntityFactory.java
Added @ApiOperation() to all endpoints with a description of what the endpoint does to make out API more clear
Replaced "@RequestMapping()" with action specific annotation. For example: "method = POST, value = "/dn-submitted")
- Replace deprecated "APPLICATION_JSON_UTF8" with proper APPLICATION_JSON
> Cleanup API

- build.gradle
Fix dependency check failure for CMS by updating the http client lib version
> DIV-6678: Fix dependency check failure div-case-maintenance-service

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
Allow respondent to query cases from given new states:
- AwaitingAlternativeService
- AwaitingProcessServerService
- AwaitingDWPResponse
Fixes https://tools.hmcts.net/jira/browse/DIV-6653
Unit test modified
> DIV-6653: Allow respondent to query cases from given new states

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseStateTest.java
https://tools.hmcts.net/jira/browse/DIV-6654
Adding cases that are in `AwaitingGeneralReferralPayment` and `GeneralConsiderationComplete` state to the list of cases returned by the service.
> DIV-6654: Map general referral states on Petitioner and Respondent apps

- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java
- src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdControllerUTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
- src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
https://tools.hmcts.net/jira/browse/DIV-6228
Adding to the list of cases that are returned to RFE to include these states 
1. AwaitingBailiffReferral
2. AwaitingBailiffService
3. IssuedToBailiff
to make it possible for the respondent or co-respondent to progress with an application if the bailiff process has already began.
> DIV-6228: Citizen Respondent submit AOS response whilst bailiff application in progress

- infrastructure/state.tf
- infrastructure/variables.tf
Fix terraform error encountered during pipeline execution
```
14:15:31  Planning failed. Terraform encountered an error while generating this plan.
14:15:31  
14:15:31  Warning: Value for undeclared variable
14:15:31  
14:15:31  The root module does not declare a variable named "instance_size" but a
14:15:31  value was found in file "aat.tfvars". If you meant to use this value, add a
14:15:31  "variable" block to the configuration.
```
> Fix terraform instance_size error
