hmcts/div-case-maintenance-service

infrastructure/main.tf, infrastructure/variables.tf, src/integrationTest/java/uk/gov/hmcts/reform/divorce/CcdPetitionServiceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/CcdSubmissionSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/CcdUpdateSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/CcdUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/RestUtil.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CitizenCaseState.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/exception/DuplicateCaseException.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdUpdateServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdUpdateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/PetitionServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/util/AuthUtilUTest.java
Petition Service Implementation
* Hardware:
* JDK:
=> [PREVIEW] Cms petitioner

infrastructure/main.tf
=> [PREVIEW] Add Provider Vault

infrastructure/main.tf
=> [PREVIEW] Remove Provider Vault

src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveAosCaseTest.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java
Fix Aos States and events
* Hardware:
* JDK:
=> [PREVIEW] fix the case state and case events

infrastructure/prod.tfvars
Update Idam urls
* Hardware:
* JDK:
=> updated idam url

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamTestSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/LinkRespondentITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
Only grant access to the case if the case is in AosAwating state
* Hardware:
* JDK:
=> [PREVIEW] Stop granting access to case if the case is not in Aos Awaiting

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java
Adding additional case states
* Hardware:
* JDK:
=> [PREVIEW] additional AOS complete states

README.md, docker-compose.yml, src/integrationTest/resources/application.properties
Application actually starts on port 4010 not 4009
=> Updated incorrect port in docs/properties

Jenkinsfile_CNP, Jenkinsfile_nightly, README.md, build.gradle, infrastructure/main.tf, src/kubernetes/deployment.template.yaml, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
=> Update demo with master

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseTest.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java
CCD Config Name changes
* Hardware:
* JDK:
=> CCD config name changes

src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseTest.java, src/integrationTest/resources/divorce-format-draft/addresses.json, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/FormatterServiceClient.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
=> DIV-3420 Removed draft transformation

.travis.yml, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseStateTest.java
Expose five new status for completed respondent case when AOS case gets queried.
Unit tests
* Hardware:
* JDK:
=> Expose five new status for completed respondent case

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseStateTest.java
Fixes # DIV-3533
* Hardware:
* JDK:
=> State mapping change

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdUpdateTest.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/CaseFormatterServiceHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/DraftStoreHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/IdamApiHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/ServiceAuthProviderHealthCheck.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
Fixed healthcheck
* Hardware:
* JDK:
=> Fix healthcheck url

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/DraftDeleteTest.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DraftStoreClient.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/DraftServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseStateTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/DeleteDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/DraftServiceImplUTest.java
Delete all drafts on delete call.
* Hardware:
* JDK:
=> fix draft delete

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdSubmissionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/client/CcdClientSupport.java, src/integrationTest/resources/ccd-submission-payload/addresses-no-hwf.json, src/integrationTest/resources/ccd-update-payload/update-addresses.json, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdSubmissionService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/BaseCcdCaseService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdSubmissionServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdSubmissionServiceImplUTest.java, src/test/resources/ccd-submission-payload/addresses-no-hwf.json
Use createhwf event when help with fees option is selected
Plea check DIV-3634 for more info
- [ x] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* JDK:
=> DIV-3634 added cratedhwf event

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdGetCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/client/CcdClientSupport.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/GetCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
The endpoint to retrieve the case from CCD.
* Hardware:
* JDK:
=> [PREVIEW] added a new endpoint to retrieve cases

src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseByIdTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
=> retrieve Petition by CaseId for Citizen

infrastructure/main.tf, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/client/CcdClientSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdAccessService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/UnlinkUserITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImplUTest.java
Added endpoint to remove user permission on a case.
- [ x] New feature (non-breaking change which adds functionality)
* Hardware:
* JDK:
=> Added remove user permission service

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java
=> Update Controller with Optional per review comments

build.gradle
fix build failure on nightly pipeline for mutation tests
=> update mutation tests

src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseByIdTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
=> Retrieve case by

infrastructure/main.tf
div-aat ASP has been split into two for resource issues:
div-1-aat and div-2-aat
Frontends and div-vs and div-fps will be part of 1.
All the remaining backends will be part of 2.
=> Moved to shared ASP 2

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/config/HttpConnectionConfiguration.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/CaseFormatterServiceHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/DraftStoreHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/IdamApiHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/ServiceAuthProviderHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/WebServiceHealthCheck.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
Added 5s timeout on healthcheck
* Hardware:
* JDK:
=> DIV-3885 added health check timeout

Jenkinsfile_nightly, security.sh
=> set up divorce cos security scan

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/AmendCaseRemovedProps.java
To clear up case when amending petition
Fixes #DIV-4303
=> DIV-4303 - added new desertion fields to AmendCaseRemovedProps

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/LinkRespondentTest.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CcdCaseProperties.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/LinkRespondentServiceImplUTest.java
Grant permission on linking if the user has the right email address.
DIV-4360
* Hardware:
* JDK:
=> DIV-4360 Grant user permission if has valid credentials

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/RootController.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/RootControllerTest.java
=> Added root controller with test

build.gradle
See:
https://github.com/hmcts/ccd-client/pull/49
In spring boot 2 sending a ContentType of */* on GET or DELETE requests doesn't seem to be working,
Small work around in the client to fix that.
Functional tests in the CCD client
=> Update CCD client version

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdGetCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/util/RestUtil.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAOSPostCompletedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
We should always check CCD, to make AAT and prod like-for-like
Fixes #DIV-4468
=> DIV-4468 - remove the checkCcd flag

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CcdCaseProperties.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/DivorceSessionProperties.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
Copying issue date from original case to "previousIssueDate" field in the new amended case.
Unit tests.
=> DIV-4531: Copying issue date when amending a case

dependency-check-suppressions.xml
Suppressing security issues.
Ran security check locally.
=> DIV-4531: Suppressing security issues

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdSubmissionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/LinkRespondentTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/AmendPetitionDraftTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdGetCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveAosCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseByIdTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java, src/integrationTest/resources/ccd-submission-payload/addresses-no-hwf.json, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CcdCaseProperties.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/DivCaseRole.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AuthIdamMockSupport.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/GetCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAOSPostCompletedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
https://tools.hmcts.net/jira/browse/DIV-4571
Filtered users based on Petitioner / Respondent role.
Filtered Amended cases on  return DN endpoint
* Hardware:
* JDK:
=> DIV-4571 Filter cases by user divorce role

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
[DIV-4529](https://tools.hmcts.net/jira/browse/DIV-4529)
* Hardware:
* JDK:
=> Add Awaiting Decree Absolute state to Petitioner mapping

build.gradle
=> Force upgrade of spring-security-crypto

Jenkinsfile_CNP
Some of them don't exist, causing the pipeline to fail
=> Remove unused secrets from Jenkins file

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CCDSearchTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SearchCasesITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
=> DIV-4695 Exposed search API

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/LinkRespondentServiceImplUTest.java
Following on from https://github.com/hmcts/div-case-maintenance-service/pull/129
This refactors the code to simplify and reduce number of lines. Also keeps the improved logging.
[Improve logging when linking (co-)respondent to case](https://tools.hmcts.net/jira/browse/DIV-4848)
=> DIV-4840 improve refactor link resp

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdBulkCaseUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java, src/integrationTest/resources/application.properties, src/integrationTest/resources/ccd-update-payload/bulk-case.json, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdUpdateService.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdUpdateServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/BulkCaseUpdateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdUpdateServiceImplUTest.java
To support [DIV-4821](https://tools.hmcts.net/jira/browse/DIV-4821)
This allows COS to call an endpoint on CMS which will allow updates on Bulk Cases.
* Hardware:
* JDK:
=> Bulk Case Update Endpoint

build.gradle, checkstyle.xml, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/CaseMaintenanceServiceApplicationTests.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/WebServiceHealthCheckUTest.java
- OWASP upgraded to v5, fixed arising vulnerabilities in swagger and elasticsearch
- Checkstyle upgraded to 8.21 with an accompanying modification to the `checkstyle.xml` file
Fixes # [DIV-5055](https://tools.hmcts.net/jira/browse/DIV-5055)
=> DIV-5055: OWASP upgrade

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdBulkCaseSubmissionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdBulkCaseUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java, src/main/resources/application.yml
Add new temporal event on bulk create 
This PR needs this config
https://github.com/hmcts/div-case-maintenance-service/pull/148
* Hardware:
* JDK:
=> Set bulk create event

README.md
=> DIV-3264: Update readme

infrastructure/main.tf, infrastructure/output.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
=> [PREVIEW] Disable swagger on prod

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java
https://tools.hmcts.net/jira/browse/DIV-4900
=> Aos Awaiting Sol state should be returned when retrived a case

README.md, build.gradle, charts/div-cms/values.aat.template.yaml, charts/div-cms/values.preview.template.yaml, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/preview.tfvars, infrastructure/variables.tf
Testing enabling swagger on ASE envs (excluding prod).
* Hardware:
* JDK:
=> Use string values for boolean swagger documentation enabled and enable parallel functional test

src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamTestSupport.java
To reduce errors in notification service.
=> change domain

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseStateTest.java
=> DIV-4559: Change all reference from DNAwaiting to AwaitingDecreeNisi

src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamTestSupport.java
Build is failing due to IDAM issue where it fails to properly create an IDAM user despite returning a success status code.
* Hardware:
* JDK:
=> Add retry mechanism for IDAM user creation in the Integration Tests

build.gradle
to fix CVE-2019-14379, CVE-2019-14439
=> UpgradeJacksonDatabind

build.gradle, dependency-check-suppressions.xml, gradle/wrapper/gradle-wrapper.properties, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/BulkCaseSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/BulkCaseUpdateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdAccessITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdUpdateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CreateDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/DeleteDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/GetCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAOSPostCompletedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAllDraftsServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SaveDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SearchCasesITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/UnlinkUserITest.java
Fixes dependencies and security issues (CVE)
=> Fix vulnerabilities 

build.gradle
Remove PMD check as it doesn't bring any value.
=> Remove PMD check

infrastructure/output.tf
Revert from #178 
Fixes pipeline
=> Revert idam change in output.tf to fix build

infrastructure/aat.tfvars, infrastructure/prod.tfvars
A revert of some changes in https://github.com/hmcts/div-case-maintenance-service/pull/178
Fixes pipeline
=> Revert breaking changes to tfvars files. Pipeline still validates those

build.gradle
This is mandatory for upcoming AKS changes.
=> Bump Health starter

Dockerfile, build.gradle
=> Upgrading AI agent

src/integrationTest/resources/divorce-format-draft/base-case-divorce-session.json, src/integrationTest/resources/divorce-format-draft/jurisdiction-6-12.json
This is related to https://github.com/hmcts/div-case-data-formatter/pull/185.
We're removing the courts info from CFS because now it it centralised in COS.
- [ x ] New feature (non-breaking change which adds functionality)
Existing tests.
=> DIV-4239: Removing courts information

build.gradle, dependency-check-suppressions.xml
=> Address CVE-2020-5398

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/DefaultHttpEntityFactory.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
- Removed spring vulnerability suppression
- Spring bumped to latest version
- Jacoco and sonarqube no longer report warnings for deprecated configs
- Healthcheck tests modified to reflect new interface introduced in spring
* Hardware:
* JDK:
=> FIX-Update spring version and modify health check tests

build.gradle, checkstyle.xml, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java
=> fix OWASP dependency check

audit.json
=> update audit json file for ignoring false positives

Jenkinsfile_CNP, dependency-check-suppressions.xml, src/integrationTest/resources/application.properties, src/main/resources/application.yml
Welsh Support added
- [X ] New feature (non-breaking change which adds functionality)
* Hardware:
* JDK:
=> Div case maintenance service demo welsh

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RPET-242
=> RPET-242: Remove deprecated method installCharts

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
=> DIV-6155: allowing petitioner to fetch case in AwaitingAmendCase state

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
https://tools.hmcts.net/jira/browse/DIV-5419
=> DIV-5419: landing-page-deemed-dispensed-not-approved

build.gradle
=> RPET-436: bump ccdStoreClient to 4.7.3

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
Fixes https://tools.hmcts.net/jira/browse/DIV-6531
* Hardware:
* JDK:
=> DIV-6531: Enable respondent to query cases in ServiceApplicationNotApproved

Dockerfile, README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, lombok.config, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionForRefusalDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CreateDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/MockSupport.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAllDraftsServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SaveDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
Upgrade Java to 11.
[RPET-263](https://tools.hmcts.net/jira/browse/RPET-263)
[RPET-263](https://tools.hmcts.net/jira/browse/RPET-263)
* Hardware:
* JDK:
=> RPET-263 Upgrade java 11

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DraftStoreClientConsumerTest.java, src/contractTest/resources/application.yml, src/contractTest/resources/json/base-case.json
=> Ta 29 data store consumer test

Jenkinsfile_nightly, build.gradle, dependency-check-suppressions.xml
1. Mutation tests fixed
2. Functional tests added to nightly build
3. Upgrading tomcat to latest version and suppressing dependency failures for a month as the issue still persists
jeremylong/DependencyCheck#2926
https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1603811478231300
=> Run functional tests in nightly build

build.gradle
=> TA-28: Fix publish pact verification

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
Allowing petitioner to fetch cases in:
- AwaitingAlternativeService
- AwaitingProcessServerService
- AwaitingDWPResponse
Fixes https://tools.hmcts.net/jira/browse/DIV-6608
Unit test updated
=> DIV-6608: allowing petitioner to fetch case in specified states

build.gradle
Fixing dependency and vulnerability issues by updating tomcat and jackson binding
=> DIV-6696: Fixing dependency issues

build.gradle
=> bump guava version

build.gradle, charts/div-cms/Chart.yaml, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionForRefusalDraftFromCaseIdServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/AmendedPetitionForRefusalDraftServiceITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/BulkCaseSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/BulkCaseUpdateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdAccessITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSolicitorSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdUpdateITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/GetCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAOSPostCompletedITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SearchCasesITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/UnlinkUserITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdSubmissionServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdUpdateServiceImplUTest.java
=> Bump base chart version to latest

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMapTest.java
https://tools.hmcts.net/jira/browse/DIV-6781
Citizen cases that are in state AosDrafted are now being sent to PFE to enable the AosDrafted landing page
=> DIV-6781: Returning cases that are in AosDrafted to PFE

build.gradle
=> updated dependencies

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/ApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseRetrievalStateMap.java, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseState.java
=> DIV-5457:Add AwaitingBailiffService

charts/div-cms/Chart.yaml, charts/div-cms/values.yaml, src/main/resources/bootstrap.yaml
=> Fix CMS logs not showing up

src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
=> add logs for amend case

charts/div-cms/Chart.yaml
Upgrading to latest version of [chart-java (3.4.5)](https://github.com/hmcts/chart-java/releases/tag/v3.4.5)
https://tools.hmcts.net/jira/browse/RPET-921
platform operations upgrade
=> RPET-921 chart java bump

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdSolicitorSubmissionTest.java, src/integrationTest/resources/ccd-submission-payload/solicitor/addresses-no-hwf.json, src/integrationTest/resources/ccd-submission-payload/solicitor/base-amended-case.json, src/integrationTest/resources/ccd-submission-payload/solicitor/base-case.json, src/integrationTest/resources/ccd-submission-payload/solicitor/bulk-case.json, src/integrationTest/resources/ccd-submission-payload/solicitor/completed-case-submitted.json, src/integrationTest/resources/ccd-submission-payload/solicitor/d8-document.json, src/integrationTest/resources/ccd-submission-payload/solicitor/how-name-changed.json, src/integrationTest/resources/ccd-submission-payload/solicitor/jurisdiction-6-12.json, src/integrationTest/resources/ccd-submission-payload/solicitor/jurisdiction-all.json, src/integrationTest/resources/ccd-submission-payload/solicitor/linked-case.json, src/integrationTest/resources/ccd-submission-payload/solicitor/reason-adultery.json, src/integrationTest/resources/ccd-submission-payload/solicitor/reason-desertion.json, src/integrationTest/resources/ccd-submission-payload/solicitor/reason-separation.json, src/integrationTest/resources/ccd-submission-payload/solicitor/reason-unreasonable-behaviour.json, src/integrationTest/resources/ccd-submission-payload/solicitor/same-sex.json
Update to test fixture due to the new organisation policy data.
=> Reverting Ignore and resolving failed test

.github/PULL_REQUEST_TEMPLATE.md, README.md, build.gradle, src/integrationTest/resources/example-application-local.properties, src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/UserServiceImpl.java, src/main/resources/example-application-aat.yml
=> Small adjustments to make CMS run locally pointing to AAT

build.gradle
=> commonsIo: '2.7'

README.md, build.gradle, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/domain/model/CaseStateTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdAccessServiceImplUTest.java
https://tools.hmcts.net/jira/browse/DFR-76
=> DFR 76 SpringBoot Update

build.gradle, charts/div-cms/Chart.yaml
Upgrade Tomcat and charts
DFR-518
- [ x] Bug fix (non-breaking change which fixes an issue)
=> DFR-518: Upgrade Tomcat and charts

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, dependency-check-suppressions.xml
Setup fortify in nightly pipeline
DFR-464
- [ x] New feature (non-breaking change which adds functionality)
=> DFR-464: Fortify setup

build.gradle
Upgrade Serenity to fix nightly pipeline
DFR-65
- [ x] Bug fix (non-breaking change which fixes an issue)
=> DFR-65: Fix nightly pipeline

Jenkinsfile_nightly, build.gradle, security.sh
Upgrade jakarta el vulnerability
DFR-549
- [ x] Bug fix (non-breaking change which fixes an issue)
=> Dfr 549 fix jakarta el vulnerabilities

config/fortify-client.properties
DFR-736: update-fortify-releaseid
=> DFR-736: update-fortify-releaseid

build.gradle
=> fix build log

charts/div-cms/Chart.yaml
=> bump java chart version

build.gradle
=> Bump springframework

build.gradle, dependency-check-suppressions.xml
DFR-1004: Published Vulnerabilities CVE-2016-1000027
=> DFR-1004: Published Vulnerabilities CVE-2016-1000027

charts/div-cms/Chart.yaml, charts/div-cms/values.yaml, dependency-check-suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdCaseRolesTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdSolicitorSubmissionTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/CcdControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSolicitorSubmissionITest.java, src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdSubmissionServiceImplUTest.java
https://tools.hmcts.net/jira/browse/DTSSE-1395
=> Autoscaling

Jenkinsfile_nightly, audit.json, src/contractTest/resources/application.properties, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/CcdUpdateSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java, src/integrationTest/resources/application.properties
=> Fix nightly pipeline

src/integrationTest/java/uk/gov/hmcts/reform/divorce/ccd/CcdSubmissionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/AmendPetitionDraftTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/AmendPetitionForRefusalDraftFromCaseIdTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/AmendPetitionForRefusalDraftTest.java
=> comment out failing tests due to citizen create event authorisations

build.gradle, dependency-check-suppressions.xml
=> Fix dependency issues

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-1712
=> DFR-1712 bump dependencies

build.gradle, charts/div-cms/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-1808
=> Dfr 1808 update chart

build.gradle, dependency-check-suppressions.xml
Reduce CVE count in Divorce
https://tools.hmcts.net/jira/browse/DFR-1492
=> Dfr 1492 CVE updates

build.gradle
DFR-3783 - Dev: Remove Jitpack dependency
=> DFR-3783 - Dev: Remove Jitpack dependency
